### ISSUE TITLE
Getting Application class not found error while running on Android 5 or 6

### ISSUE THREAD

**Issue by khagesh1998** [retrostreams/android-retrofuture#5]
The JDK Version in the app is being used is JAVA_11.
Kindly help.

```
  Process: com.app.staging, PID: 21740
                                                                                                    java.lang.RuntimeException: Unable to instantiate application com.example.Application: java.lang.ClassNotFoundException: Didn't find class  com.example.Application on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.app.staging-1/base.apk"],nativeLibraryDirectories=[/data/app/com.app.staging-1/lib/arm, /data/app/com.app.staging-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:581)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4817)
                                                                                                    	at android.app.ActivityThread.access$1700(ActivityThread.java:166)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:148)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5619)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class  com.example.Application on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.app.staging-1/base.apk"],nativeLibraryDirectories=[/data/app/com.app.staging-1/lib/arm, /data/app/com.app.staging-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:988)
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:576)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4817) 
                                                                                                    	at android.app.ActivityThread.access$1700(ActivityThread.java:166) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    	at android.os.Looper.loop(Looper.java:148) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5619) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
                                                                                                    	Suppressed: java.lang.NoClassDefFoundError: com.example.Application
                                                                                                    		at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                                                    		at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                                                    		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                                                    		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                                                    		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                                                    		... 13 more
                                                                                                    	Suppressed: java.lang.ClassNotFoundException: com.example.Application
                                                                                                    		at java.lang.Class.classForName(Native Method)
                                                                                                    		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                                    		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                                    		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                                    		... 12 more
                                                                                                    	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by stefan-zobel** [comment]
@khagesh1998

What makes you believe that your problem is associated with android-retrofuture in any way?
From the stacktrace you've provided I can't see any evidence for that.

**Comment by khagesh1998** [comment]
Upon removing the backport dependencies provided by the Retrofuture, the app works fine . 
```
retrofix('net.sourceforge.streamsupport:android-retrostreams:1.7.4')
retrofix('net.sourceforge.streamsupport:android-retrofuture:1.7.4')
```

On Android >6 the backport dependencies are not needed as per the hivemq doc. We need to add the backport dependencies for Android <= 6 as per the below doc provided. 
 https://hivemq.github.io/hivemq-mqtt-client/docs/installation/android/#android-api-levels-below-24

**Comment by khagesh1998** [comment]
May be some dependencies got mixed up in my project which might have caused the crash.
As per the down digging on sample app we have found that if we add facebook-sdk with the retrofix backport dependencies, the app crashes  with above stack provided.

https://github.com/facebook/facebook-android-sdk

**Comment by stefan-zobel** [comment]
I'm not responsible for [android-retrofix](https://github.com/SgtSilvio/android-retrofix) and I can assure you that android-retrofuture is working fine on Lollipop / Marshmallow when you use the API from the java9.util package directly.

Anyway, you'll have to provide more evidence than a "java.lang.ClassNotFoundException: Didn't find class  **----packagename.application----****" if you want to put anyone in the position to look into your problem.

**Comment by stefan-zobel** [comment]
@khagesh1998

Good luck!
